'use strict';
const el=id=>document.getElementById(id);
let lang=location.hash==='#en'?'en':'ja', locked=false;
const txt=(ja,en)=>lang==='ja'?ja:en;
function fresh(){return {version:Stage5.version,scene:0,input:{...Stage5.defaults},choices:{a:'none',b:'none'},prediction:'unsure',confidence:50,answers:{reason:'',explanation:'',revision:'',transfer:''}};}
let state=fresh();
const labels={aGround:['A：確認経路','A: checking'],aAudit:['A：監査経路','A: auditing'],bGround:['B：確認経路','B: checking'],bAudit:['B：監査経路','B: auditing'],alpha:['α：作用強度','Alpha: strength'],beta:['β：作用強度','Beta: strength']};
for(const [key,pair]of Object.entries(labels)){const label=document.createElement('label'),span=document.createElement('span'),input=document.createElement('input');span.dataset.ja=pair[0];span.dataset.en=pair[1];input.id=key;input.type='number';input.min='0';input.max='100';input.step='any';label.append(span,input);el('initialInputs').append(label);}
for(const id of ['choiceA','choiceB'])for(const [value,ja,en]of [['none','何もしない（0）','No change (0)'],['ground','確認経路を増やす（25）','Increase checking (25)'],['audit','監査経路を増やす（25）','Increase auditing (25)']]){const o=document.createElement('option');o.value=value;o.dataset.ja=ja;o.dataset.en=en;el(id).append(o);}
function hydrate(){for(const[k,v]of Object.entries(state.input))el(k).value=v;el('prediction').value=state.prediction;el('confidence').value=state.confidence;for(const[k,v]of Object.entries(state.answers))el(k).value=v;el('choiceA').value=state.choices.a;el('choiceB').value=state.choices.b;}
function capture(){const next=structuredClone(state);for(const key of Object.keys(labels)){if(!el(key).checkValidity()||el(key).value==='')throw Error();next.input[key]=Number(el(key).value);}if(!el('confidence').checkValidity()||el('confidence').value==='')throw Error();next.confidence=Number(el('confidence').value);next.prediction=el('prediction').value;for(const key of Object.keys(next.answers))next.answers[key]=el(key).value;next.choices={a:el('choiceA').value,b:el('choiceB').value};state=Stage5.decode(JSON.stringify(next));}
function table(id,rows,before){const table=document.createElement('table'),head=document.createElement('thead'),tr=document.createElement('tr');for(const title of [txt('地域／作用','Sector / action'),txt('拡散','Spread'),txt('監査で見えない部分','Unseen by audit')]){const th=document.createElement('th');th.scope='col';th.textContent=title;tr.append(th);}head.append(tr);table.append(head);const body=document.createElement('tbody');rows.forEach((r,i)=>{const row=document.createElement('tr');const fmt=key=>r[key].toFixed(2)+(before?' ('+txt('初回比 ','vs initial ')+(r[key]-before[i][key]).toFixed(2)+')':'');for(const value of [r.sector.toUpperCase()+'/'+(r.operator==='alpha'?'α':'β'),fmt('spread'),fmt('hidden')]){const td=document.createElement('td');td.textContent=value;row.append(td);}body.append(row);});table.append(body);el(id).replaceChildren(table);}
function render(focus=true){document.documentElement.lang=lang;document.querySelectorAll('[data-ja]').forEach(e=>e.textContent=e.dataset[lang]);el('language').textContent=lang==='ja'?'English':'日本語';document.querySelectorAll('[data-scene]').forEach(e=>e.hidden=Number(e.dataset.scene)!==state.scene);el('progress').textContent=txt('場面 ','Scene ')+(state.scene+1)+' / 8';el('back').disabled=state.scene===0;el('next').hidden=state.scene===7;for(const key of [...Object.keys(labels),'prediction','confidence','reason'])el(key).disabled=locked;
const r=Stage5.evaluate(state.input,state.choices);table('original',r.original);table('swapped',r.swapped,r.original);table('factorial',r.factorial);table('repaired',r.repaired,r.original);
el('initialSummary').textContent=Object.entries(state.input).map(([k,v])=>txt(...labels[k])+': '+v).join(' / ');
el('swapCaveat').textContent=state.input.alpha===state.input.beta?txt('αとβの強さは同じです。この式では交換で結果が変わらないのは当然です。人物の影響が小さいという証拠にはなりません。次の実験では強さを変えてみてください。','Alpha and beta have equal strength. Unchanged outcomes after swapping follow directly from the formula; they are not evidence that people have little influence. Try unequal strengths in a new experiment.'):txt('今回は作用強度が異なります。交換による差を表で確認してください。地域条件を固定したモデル内の差で、実社会の人物効果を推定したものではありません。','Action strengths differ here. Inspect the swap differences above. These are within-model contrasts at fixed sector conditions, not estimates of real-world personal effects.');
el('cost').textContent=txt('使用予算：','Budget used: ')+'A '+r.cost.a+'/25 · B '+r.cost.b+'/25';
const prediction={a:'A',b:'B',equal:txt('同じ','Equal'),unsure:txt('判断保留','Unsure')}[state.prediction];const delta=r.original[0].spread-r.original[1].spread;const observed=Math.abs(delta)<1e-10?txt('同じ','Equal'):(delta>0?'A':'B');el('predictionReview').textContent=txt('最初の予想：','Initial prediction: ')+prediction+txt(' ／ 確信度：',' / Confidence: ')+state.confidence+txt(' ／ 初回の拡散が大きい側：',' / Greater initial spread: ')+observed;el('reasonReview').textContent=txt('最初の理由：','Initial reason: ')+state.answers.reason;
if(focus)document.querySelector('[data-scene="'+state.scene+'"] h2').focus();}
function safe(fn){try{fn();el('status').textContent='';}catch{el('status').textContent=txt('入力範囲や記録の形式を確認してください。','Check input ranges or record format.');}}
el('next').onclick=()=>safe(()=>{capture();if(state.scene===1)locked=true;state.scene=Math.min(7,state.scene+1);render();});el('back').onclick=()=>safe(()=>{capture();state.scene=Math.max(0,state.scene-1);render();});
el('language').onclick=()=>safe(()=>{capture();lang=lang==='ja'?'en':'ja';render(false);});
el('restart').onclick=()=>{if(!confirm(txt('現在の記録を消して、新しい実験を始めますか？ 残す場合は先にJSONを保存してください。','Clear this record and start a new experiment? Export JSON first to keep it.')))return;state=fresh();locked=false;hydrate();render();};
el('save').onclick=()=>safe(()=>{capture();const data={...state,locked,result:Stage5.evaluate(state.input,state.choices)};const raw=JSON.stringify(data,null,2);Stage5.decode(raw);const url=URL.createObjectURL(new Blob([raw],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='stage5-learning-record.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
el('load').onchange=async()=>{try{const f=el('load').files[0];if(!f)return;if(f.size>100000)throw Error();const raw=await f.text();const next=Stage5.decode(raw);const parsed=JSON.parse(raw);if(typeof parsed.locked!=='boolean')throw Error();state=next;locked=parsed.locked||next.scene>=2;hydrate();render();el('status').textContent=txt('記録を読み戻し、結果を再計算しました。','Record imported; results recomputed.');}catch{el('status').textContent=txt('読み込めません。形式・モデル版・100KB以下を確認してください。','Import failed. Check format, model version and the 100KB limit.');}finally{el('load').value='';}};
hydrate();render(false);
